management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: beans,env
  endpoint:
    health:
      show-details: ALWAYS

server:
  servlet:
    context-path: /sigo-process