spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:127.0.0.1}:${DATABASE_PORT:3306}/${DATABASE_NAME:sigo_standard}?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.jdbc.Driver
    username: ${DATABASE_USERNAME:sigo}
    password: ${DATABASE_PASSWORD:sigo}
  flyway:
    baseline-on-migrate: false
    enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: beans,env
  endpoint:
    health:
      show-details: ALWAYS