apiVersion: apps/v1
kind: Deployment
metadata:
  name: sigo-standard-deployment 
  namespace: sigo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sigo-standard
  template:
    metadata:
      labels:
        app: sigo-standard
    spec:
      containers:
        - name: sigo-standard
          image: 630947548599.dkr.ecr.us-east-1.amazonaws.com/sigo-standard:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
          - name: DATABASE_HOST
            value: "mysql"
          - name: DATABASE_NAME
            value: "sigo_standard"
          - name: DATABASE_USERNAME
            value: "admin"
          - name: DATABASE_PASSWORD
            value: "Sigo12454"