apiVersion: apps/v1
kind: Deployment
metadata:
  name: sigo-process-deployment 
  namespace: sigo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sigo-process
  template:
    metadata:
      labels:
        app: sigo-process
    spec:
      containers:
        - name: sigo-process
          image: 630947548599.dkr.ecr.us-east-1.amazonaws.com/sigo-process:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080